version: '3'
name: softgeek-lotery-db
services:
  # MySQL
  db:
    container_name: mysql8-softgeek-lotery
    hostname: LoteryHost
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: Adr1an978**
      MYSQL_DATABASE: softgeek-lotery-db
#      MYSQL_USER: aa5a62_db5
#      MYSQL_PASSWORD: Pasa2024
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '3308:3306'
